name: Pelican site CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - main
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up stork
      run: |
          wget https://files.stork-search.net/releases/v1.6.0/stork-ubuntu-20-04
          chmod +x stork-ubuntu-20-04
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
            python -m pip install --upgrade pip
            pip install poetry
            poetry install
    - name: Build the site
      run: |
            poetry run pelican content -s publishconf.py
    - name: Upload
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./output
    - name: Deploy
      uses: actions/deploy-pages@v2